module main

import vory
import db.pg
import lib.dbv

struct PgConfig{}
pub fn new_pgconfig() pg.Config{
	return pg.Config{
		host: '127.0.0.1'
		port: 5432
		user: 'postgres'
		password: '12345'
		dbname: 'vory'
	}
}

fn main(){
	v := vory.new()

	conn := v.connect( new_pgconfig() )

	// set up table
	// query := "CREATE TABLE users();"
	// query := "ALTER TABLE users ADD id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;"
	// query := "ALTER TABLE users ADD name VARCHAR(50); ALTER TABLE users ADD email VARCHAR(100);"
	// query := "INSERT INTO users (name, email) VALUES ('yale', 'yale918@gmail.com');"

	// SELECT column_name, data_type
	// FROM information_schema.columns
	// WHERE table_schema = 'public' AND table_name = 'staff_info';

	// column := "SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users';"
	//
	// column_name := conn.exec(column) or { panic(err) }
	//
	// query := "select * from users;"
	// rows := conn.exec(query) or { panic(err) }

	rows, column_name := dbv.query(conn, "users")

	users_json := dbv.row_tojson(column_name, rows)
	println("\nusers_json: ${users_json}")

	users := dbv.json_touser(users_json)
	println("\nusers: ${users}")

}
