CREATE TABLE "users"();
ALTER TABLE "users" ADD "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE "users" ADD "name" VARCHAR(50);
ALTER TABLE "users" ADD "email" VARCHAR(50);
ALTER TABLE "users" ADD "password" VARCHAR(50);

CREATE TABLE "profile"();
ALTER TABLE "profile" ADD "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE "profile" ADD "user_id" INT;
ALTER TABLE "profile" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "profile" ADD "photo" VARCHAR(200);

CREATE TABLE "post"();
ALTER TABLE "post" ADD "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE "post" ADD "user_id" INT;
ALTER TABLE "post" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "post" ADD "title" VARCHAR(200);
ALTER TABLE "post" ADD "contents" VARCHAR(300);

CREATE TABLE "comment"();
ALTER TABLE "comment" ADD "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE "comment" ADD "post_id" INT;
ALTER TABLE "comment" ADD FOREIGN KEY ("post_id") REFERENCES "post" ("id");

CREATE TABLE "comment_detail"();
ALTER TABLE "comment_detail" ADD "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE "comment_detail" ADD "comment_id" INT;
ALTER TABLE "comment_detail" ADD FOREIGN KEY ("comment_id") REFERENCES "comment" ("id");
ALTER TABLE "comment_detail" ADD "content" VARCHAR(300);